"""Headless replay for trajectories generated by :mod:`motion.planner`."""

from __future__ import annotations

from dataclasses import dataclass
from math import hypot

from .geometry import ArmGeometry, Point
from .kinematics import ArmPose, forward_kinematics
from .trajectory import MotionPlan
from .validation import validate_operation


@dataclass(frozen=True)
class ReplaySample:
    operation: str
    sample_index: int
    arm1_pose: ArmPose
    arm2_pose: ArmPose


@dataclass(frozen=True)
class ReplayResult:
    samples: tuple[ReplaySample, ...]
    final_errors_mm: dict[str, float]
    validation_errors: tuple[str, ...]


def replay_plan(
    plan: MotionPlan,
    geometries: dict[str, ArmGeometry],
    calibrations,
    tolerance_mm: float = 0.001,
) -> ReplayResult:
    """Replay every joint point through production FK and check final tip error."""
    samples: list[ReplaySample] = []
    errors: list[str] = []
    final_errors: dict[str, float] = {}
    for operation in plan.operations:
        for error in validate_operation(operation, geometries, calibrations):
            errors.append(f"{operation.name}: {error.message}")
        for index, sample in enumerate(operation.samples):
            samples.append(ReplaySample(
                operation.name, index,
                forward_kinematics(sample.state.arm1, geometries["arm1"]),
                forward_kinematics(sample.state.arm2, geometries["arm2"]),
            ))
        final_pose = forward_kinematics(operation.target.for_arm(operation.moving_arm), geometries[operation.moving_arm])
        error_mm = hypot(final_pose.W[0] - operation.requested_machine_target[0], final_pose.W[1] - operation.requested_machine_target[1])
        final_errors[operation.moving_arm] = error_mm
        if error_mm > tolerance_mm:
            errors.append(f"{operation.name}: final tip error {error_mm:.6f} mm exceeds {tolerance_mm:.6f} mm")
    return ReplayResult(tuple(samples), final_errors, tuple(errors))
